export const LOGGED_OUT  = 'LOGGED_OUT'
export const IS_LOGGING_IN = 'IS_LOGGING_IN';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const RECIEVED_ERROR = 'RECIEVED_ERROR ';


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS ';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS ';
export const ERROR_RECIEVING_PRODUCTS = 'ERROR_RECIEVING_PRODUCTS ';
