export const LOGGED_OUT  = 'LOGGED_OUT'
export const IS_LOGGING_IN = 'IS_LOGGING_IN';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const RECIEVED_ERROR = 'RECIEVED_ERROR ';


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS ';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS ';
export const ERROR_RECIEVING_PRODUCTS = 'ERROR_RECIEVING_PRODUCTS ';
export const UPDATED_PRODUCTS = 'UPDATED_PRODUCTS';


export const BARCODE_OPEN = 'BARCODE_OPEN';
export const BARCODE_DATA_CLOSE = 'BARCODE_DATA_CLOSE';


export const DETAIL_BARCODE_OPEN = 'DETAIL_BARCODE_OPEN';
export const DETAIL_BARCODE_DATA_CLOSE = 'DETAIL_BARCODE_DATA_CLOSE';



export const MISSING_FETCH_PRODUCTS = 'MISSING_FETCH_PRODUCTS ';
export const MISSING_FETCHED_PRODUCTS = 'MISSING_FETCHED_PRODUCTS ';
export const MISSIMG_ERROR_RECIEVING_PRODUCTS = 'MISSIMG_ERROR_RECIEVING_PRODUCTS ';


export const FETCH_DATA = 'FETCH_DATA ';
export const FETCHED_DATA = 'FETCHED_DATA ';
export const ERROR_RECIEVING_DATA = 'ERROR_RECIEVING_DATA ';

export const ALERT_GENERAL_CASE = 'ALERT_GENERAL_CASE';
export const ALERT_GENERAL_CASE_CLOSE = 'ALERT_GENERAL_CASE_CLOSE'

export const ALERT_TWIN_CASE = 'ALERT_TWIN_CASE'
export const ALERT_TWIN_CASE_CLOSE = 'ALERT_TWIN_CASE_CLOSE'

export const ALERT_NO_MORE_PRODUCTS = 'ALERT_NO_MORE_PRODUCTS'
export const ALERT_NO_MORE_PRODUCTS_CLOSE = 'ALERT_NO_MORE_PRODUCTS_CLOSE'
