
export const IS_LOGGING_IN = 'IS_LOGGING_IN';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const RECIEVED_ERROR = 'RECIEVED_ERROR ';



export const FETCH_PRODUCTS = 'FETCH_PRODUCTS ';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS ';
export const ERROR_RECIEVING_PRODUCTS = 'ERROR_RECIEVING_PRODUCTS ';
export const CHANGE_PRODUCT_STATUS= 'CHANGE_PRODUCT_STATUS';

export const FETCH_DATA = 'FETCH_DATA ';
export const FETCHED_DATA = 'FETCHED_DATA ';
export const ERROR_RECIEVING_DATA = 'ERROR_RECIEVING_DATA ';
export const CHANGE_FETCHDATA_STATUS = 'CHANGE_FETCHDATA_STATUS';

export const IS_LOGGING_OUT = 'IS_LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGING_OUT_ERROR = 'LOGGING_OUT_ERROR';
export const CHANGE_LOG_OUT_STATUS = 'CHANGE_LOG_OUT_STATUS'

export const SYNCING_PRODUCTS= 'SYNCING_PRODUCTS';
export const SYNCED_PRODUCTS = 'SYNCED_PRODUCTS ';
export const ERROR_SYNCING_PRODUCTS = 'ERROR_SYNCING_PRODUCTS ';

export const SAVED_PRODUCTS = 'SAVED_PRODUCTS';
export const CLEAR_SAVED_PRODUCTS = 'CLEAR_SAVED_PRODUCTS'

export const SAVED_SYNC_PRODUCTS = 'SAVED_SYNC_PRODUCTS'

export const CLEAR_SYNC_PRODUCTS = 'CLEAR_SYNC_PRODUCTS'

export const CHANGE_SAVED_DATA_STATUS = 'CHANGE_SAVED_DATA_STATUS'
